{% set name = "boto3_type" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/boto3_type-{{ version }}.tar.gz
  sha256: e9024e2fae3b8a86b2b6b41f0adc8eb5252d93eaa3d32c6bcf3c767e8f96cfdb

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - boto3
    - botocore
    - python >={{ python_min }}

test:
  imports:
    - boto3_type
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/j4c0bs/boto3-type
  summary: Boto3 service type check
  dev_url: https://github.com/j4c0bs/boto3-type
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
